import random
# THEME = {1: , 2: , 3: , 4: , 5: , 6: , 7: , 8: , 9: , 10: , 11: , 12: , 13: , 14: , 15: , 16: , 17: , 18: , 19: , 20: , 21: , 22: , 23: , 24: , 25: , 26: , 27: , 28: , 29: , 30: , 31: , 32: , 33: , 34: , 35: , 36: , 37: , 38: , 39: , 40: , 41: , 42: , 43: , 44: , 45: , 46: , 47: , 48: , 49: , 50: }

Nombres = {1: "1", 2: "2", 3: "3", 4: "4", 5: "5", 6: "6", 7: "7", 8: "8", 9: "9", 10: "10", 11: "11", 12: "12", 13: "13", 14: "14", 15: "15", 16: "16", 17: "17", 18: "18", 19: "19", 20: "20", 21: "21", 22: "22", 23: "23", 24: "24",
           25: "25", 26: "26", 27: "27", 28: "28", 29: "29", 30: "30", 31: "31", 32: "32", 33: "33", 34: "34", 35: "35", 36: "36", 37: "37", 38: "38", 39: "39", 40: "40", 41: "41", 42: "42", 43: "43", 44: "44", 45: "45", 46: "46", 47: "47", 48: "48", 49: "49", 50: "50"}

Drapeaux = {1: "Drapeaux\DrapeauUSA.png", 2: "Drapeaux\DrapeauFrance.png", 3: "Drapeaux\DrapeauQatar.png", 4: "Drapeaux\DrapeauAfriqueDuSud.png", 5: "Drapeaux\DrapeauVatican.png", 6: "Drapeaux\DrapeauTuvalu.png", 7: "Drapeaux\DrapeauLuxembourg.png", 8: "Drapeaux\DrapeauNouvelleZelande.png", 9: "Drapeaux\DrapeauAustralie.png", 10: "Drapeaux\DrapeauSingapour.png", 11: "Drapeaux\DrapeauTurquie.png", 12: "Drapeaux\DrapeauTunisie.png", 13: "Drapeaux\DrapeauMaroc.png", 14: "Drapeaux\DrapeauAlgerie.png", 15: "Drapeaux\DrapeauEgypte.png", 16: "Drapeaux\DrapeauMyanmar.png", 17: "Drapeaux\DrapeauBangladesh.png", 18: "Drapeaux\DrapeauMongolie.png", 19: "Drapeaux\DrapeauMonaco.png", 20: "Drapeaux\DrapeauAndorre.png", 21: "Drapeaux\DrapeauLituanie.png", 22: "Drapeaux\DrapeauDanemark.png", 23: "Drapeaux\DrapeauPaysBas.png", 24: "Drapeaux\DrapeauBelgique.png", 25: "Drapeaux\DrapeauGroenland.png",
            26: "Drapeaux\DrapeauIslande.png", 27: "Drapeaux\DrapeauChypre.png", 28: "Drapeaux\DrapeauMalte.png", 29: "Drapeaux\DrapeauKazakhstan.png", 30: "Drapeaux\DrapeauInde.png", 31: "Drapeaux\DrapeauCoreeDuNord.png", 32: "Drapeaux\DrapeauCoreeDuSud.png", 33: "Drapeaux\DrapeauChine.png", 34: "Drapeaux\DrapeauJapon.png", 35: "Drapeaux\DrapeauRussie.png", 36: "Drapeaux\DrapeauUkraine.png", 37: "Drapeaux\DrapeauRepubliqueTcheque.png", 38: "Drapeaux\DrapeauAutriche.png", 39: "Drapeaux\DrapeauPologne.png", 40: "Drapeaux\DrapeauPortugal.png", 41: "Drapeaux\DrapeauCanada.png", 42: "Drapeaux\DrapeauArgentine.png", 43: "Drapeaux\DrapeauBresil.png", 44: "Drapeaux\DrapeauAllemagne.png", 45: "Drapeaux\DrapeauNorvege.png", 46: "Drapeaux\DrapeauFinlande.png", 47: "Drapeaux\DrapeauSuede.png", 48: "Drapeaux\DrapeauAnglais.png", 49: "Drapeaux\DrapeauEspagne.png", 50: "Drapeaux\DrapeauItalie.png"}

Nom_drapeaux = {'USA': 'DrapeauUSA.png', 'France': 'DrapeauFrance.png', 'Qatar': "DrapeauQatar.png", 'Afrique du Sud': "DrapeauAfriqueDuSud.png", 'Vatican': "DrapeauVatican.png", 'Tuvalu': "DrapeauTuvalu.png", 'Luxembourg': "DrapeauLuxembourg.png", 'Nouvelle Zélande': "DrapeauNouvelleZélande.png", 'Australie': "DrapeauAustralie.png", 'Singapour': "DrapeauSingapour.png", 'Turquie': "DrapeauTurquie.png", 'Tunisie': "DrapeauTunisie.png", 'Maroc': "DrapeauMaroc.png", 'Algérie': "DrapeauAlgerie.png", 'Egypte': "DrapeauEgypte.png", 'Myanmar': "DrapeauMyanmar.png", 'Bangladesh': "DrapeauBangladesh.png", 'Mongolie': "DrapeauMongolie.png", 'Monaco': "DrapeauMonaco.png", 'Andorre': "DrapeauAndorre.png", 'Lituanie': "DrapeauLituanie.png", 'Danemark': "DrapeauDanemark.png", 'Pays-Bas': "DrapeauPaysBas.png", 'Belgique': "DrapeauBelgique.png", 'Groenland': "DrapeauGroenland.png",
                'Islande': "DrapeauIslande.png", 'Chypre': "DrapeauChypre.png", 'Malte': "DrapeauMalte.png", 'Kazakhstan': "DrapeauKazakhstan.png", 'Inde': "DrapeauInde.png", 'Corée du Nord': "DrapeauCoreeDuNord.png", 'Corée du Sud': "DrapeauCoreeDuSud.png", 'Chine': "DrapeauChine.png", 'Japon': "DrapeauJapon.png", 'Russie': "DrapeauRussie.png", 'Ukraine': "DrapeauUkraine.png", "République Tchèque": "DrapeauRepubliqueTchèque.png", 'Autriche': "DrapeauAutriche.png", 'Pologne': "DrapeauPologne.png", 'Portugal': "DrapeauPortugal.png", 'Canada': "DrapeauCanada.png", 'Argentine': "DrapeauArgentine.png", 'Brésil': "DrapeauBrésil.png", 'Allemagne': "DrapeauAllemagne.png", 'Norvege': "DrapeauNorvege.png", 'Finlande': "DrapeauFinlande.png", 'Suède': "DrapeauSuede.png", 'Angleterre': "DrapeauAnglais.png", 'Espagne': "DrapeauEspagne.png", 'Italie': "DrapeauItalie.png"}

Animaux = {1: "Animaux/Abeille.png", 2: "Animaux/Aigle.png", 3: "Animaux/Autruche.png", 4: "Animaux/Axolotl.png", 5: "Animaux/Baleine.png", 6: "Animaux/Belette.png", 7: "Animaux/Blaireau.png", 8: "Animaux/Cachalot.png", 9: "Animaux/Castor.png", 10: "Animaux/Cerf.png", 11: "Animaux/Cheval.png", 12: "Animaux/Cobra.png", 13: "Animaux/Coq.png", 14: "Animaux/Crocodile.png", 15: "Animaux/Cygne.png", 16: "Animaux/Dauphin.png", 17: "Animaux/Elan.png", 18: "Animaux/Elephant.png", 19: "Animaux/Faisan.png", 20: "Animaux/Fourmillier.png", 21: "Animaux/Gazelle.png", 22: "Animaux/Gorille.png", 23: "Animaux/Herisson.png", 24: "Animaux/Hyene.png", 25: "Animaux/Kangourou.png",
           26: "Animaux/Koala.png", 27: "Animaux/Leopard.png", 28: "Animaux/Lievre.png", 29: "Animaux/Lion.png", 30: "Animaux/Loup.png", 31: "Animaux/Loutre.png", 32: "Animaux/MakiKata.png", 33: "Animaux/Manchot.png", 34: "Animaux/Mygale.png", 35: "Animaux/Ornithorynque.png", 36: "Animaux/Ouistiti.png", 37: "Animaux/Ours.png", 38: "Animaux/Panda.png", 39: "Animaux/Panthere.png", 40: "Animaux/Paresseux.png", 41: "Animaux/Pelican.png", 42: "Animaux/Puma.png", 43: "Animaux/Renard.png", 44: "Animaux/Requin.png", 45: "Animaux/Sanglier.png", 46: "Animaux/Serval.png", 47: "Animaux/Suricate.png", 48: "Animaux/Tigre.png", 49: "Animaux/Tortue.png", 50: "Animaux/Vautour.png"}

Pokemon = {1: "Pokemon/Amonita.png", 2: "Pokemon/Arcanin.png", 3: "Pokemon/Axoloto.png", 4: "Pokemon/Bulbizarre.png", 5: "Pokemon/Capumain.png", 6: "Pokemon/Carapuce.png", 7: "Pokemon/Chenipan.png", 8: "Pokemon/Dialga.png", 9: "Pokemon/Doduo.png", 10: "Pokemon/Dracaufeu.png", 11: "Pokemon/Elecsprint.png", 12: "Pokemon/Electrode.png", 13: "Pokemon/Evoli.png", 14: "Pokemon/Gardevoir.png", 15: "Pokemon/Goupix.png", 16: "Pokemon/Gravalanch.png", 17: "Pokemon/Gruikui.png", 18: "Pokemon/Insecateur.png", 19: "Pokemon/Jungko.png", 20: "Pokemon/Kaiminus.png", 21: "Pokemon/Krabby.png", 22: "Pokemon/Leviator.png", 23: "Pokemon/Lokhlass.png", 24: "Pokemon/Lucario.png", 25: "Pokemon/Magmar.png",
           26: "Pokemon/Magneti.png", 27: "Pokemon/Malosse.png", 28: "Pokemon/Metalosse.png", 29: "Pokemon/Miaouss.png", 30: "Pokemon/Moufflair.png", 31: "Pokemon/Mustebouee.png", 32: "Pokemon/NidoranMale.png", 33: "Pokemon/Onyx.png", 34: "Pokemon/Palkia.png", 35: "Pokemon/Parasect.png", 36: "Pokemon/Pikachu.png", 37: "Pokemon/Ponita.png", 38: "Pokemon/Poussifeu.png", 39: "Pokemon/Ronflex.png", 40: "Pokemon/Roucool.png", 41: "Pokemon/Sablaireau.png", 42: "Pokemon/Sharpedo.png", 43: "Pokemon/Shaymin.png", 44: "Pokemon/Simiabraz.png", 45: "Pokemon/Smogogo.png", 46: "Pokemon/Stari.png", 47: "Pokemon/Tadmorv.png", 48: "Pokemon/Taupiqueur.png", 49: "Pokemon/Tiplouf.png", 50: "Pokemon/Tortipouss.png"}

Politiciens = {1: "Politiciens/AdrienQuattenens.png", 2: "Politiciens/AlainJuppe.png", 3: "Politiciens/AlexisCorbiere.png", 4: "Politiciens/AnneHidalgo.png", 5: "Politiciens/ArletteLaguiller.png", 6: "Politiciens/BenoitHamon.png", 7: "Politiciens/BrunoLeMaire.png", 8: "Politiciens/CharlesDeGaulle.png", 9: "Politiciens/DanieleObono.png", 10: "Politiciens/DominiqueStraussKahn.png", 11: "Politiciens/EdouardPhilippe.png", 12: "Politiciens/ElisabethBorne.png", 13: "Politiciens/EmmanuelMacron.png", 14: "Politiciens/EricDupontMoretti.png", 15: "Politiciens/EricZemmour.png", 16: "Politiciens/FabienRoussel.png", 17: "Politiciens/FlorianPhilippot.png", 18: "FrancoisBayrou.png", 19: "Politiciens/FrancoisFillon.png", 20: "Politiciens/FrancoisHollande.png", 21: "Politiciens/FrancoisMiterrand.png", 22: "Politiciens/FrancoisRuffin.png", 23: "Politiciens/GabrielAttal.png", 24: "Politiciens/GeorgesPompidou.png", 25: "Politiciens/GeraldDarmanin.png",
               26: "Politiciens/JacquesChirac.png", 27: "Politiciens/JeanLucMelenchon.png", 28: "Politiciens/JeanMarieLePen.png", 29: "Politiciens/JordanBardella.png", 30: "Politiciens/LaurentWauqiez.png", 31: "Politiciens/LionelJospin.png", 32: "Politiciens/LouisBoyard.png", 33: "Politiciens/MarineLePen.png", 34: "Politiciens/MarionMarechal.png", 35: "Politiciens/MarleneSchiappa.png", 36: "Politiciens/MichelRocard.png", 37: "Politiciens/NicolasDupontAignan.png", 38: "Politiciens/NicolasHulot.png", 39: "Politiciens/NicolasSarkozy.png", 40: "Politiciens/PatrickBalakany.png", 41: "Politiciens/PhilippeDeVilliers.png", 42: "Politiciens/PhilippePoutou.png", 43: "Politiciens/RaquelGarrido.png", 44: "Politiciens/SandrineRousseau.png", 45: "Politiciens/SegoleneRoyal.png", 46: "Politiciens/SibethNdiaye.png", 47: "Politiciens/StanislasRigault.png", 48: "Politiciens/ValeriePecresse.png", 49: "Politiciens/ValeryGiscarddEstaing.png", 50: "Politiciens/YannickJadot.png"}

Logos = {1: "Logos/Acura.png", 2: "Logos/AlphaRomeo.png", 3: "Logos/Audi.png", 4: "Logos/Autobianchi.png", 5: "Logos/BMW.png", 6: "Logos/Buick.png", 7: "Logos/Cadillac.png", 8: "Logos/Changan.png", 9: "Logos/Chevrolet.png", 10: "Logos/Citroen.png", 11: "Logos/Corvette.png", 12: "Logos/Daewoo.png", 13: "Logos/Dodge.png", 14: "Logos/Ferrari.png", 15: "Logos/Fiat.png", 16: "Logos/Foton.png", 17: "Logos/Hafei.png", 18: "Logos/Holden.png", 19: "Logos/Honda.png", 20: "Logos/Hyundai.png", 21: "Logos/Infinity.png", 22: "Logos/Jaguar.png", 23: "Logos/Lada.png", 24: "Logos/Lancia.png", 25: "Logos/Lexus.png",
         26: "Logos/Lincoln.png", 27: "Logos/Maserati.png", 28: "Logos/Maybach.png", 29: "Logos/Mazda.png", 30: "Logos/Mercedes.png", 31: "Logos/Mercury.png", 32: "Logos/Mitsubishi.png", 33: "Logos/Mustang.png", 34: "Logos/Oldsmobile.png", 35: "Logos/Opel.png", 36: "Logos/Peugeot.png", 37: "Logos/Polestar.png", 38: "Logos/Pontiac.png", 39: "Logos/Porsche.png", 40: "Logos/Renault.png", 41: "Logos/Saab.png", 42: "Logos/Seat.png", 43: "Logos/Skoda.png", 44: "Logos/Smart.png", 45: "Logos/Subaru.png", 46: "Logos/Tesla.png", 47: "Logos/Toyota.png", 48: "Logos/Trabant.png", 49: "Logos/Vauxhall.png", 50: "Logos/Volkswagen.png"}


def random_theme(theme, nb_de_paires):
    # fonction pour sélectionner aléatoirement dans ce dictionnaire les photos
    # renvoie une liste de path
    M = []
    compteur = 1
    L = theme.values()
    L = list(L)
    while compteur <= nb_de_paires:
        attribut = random.randint(0, len(L)-1)
        M.append(L[attribut])
        del L[attribut]
        compteur += 1
    return M
